server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

ingester: {}

compactor: {}

querier:
  frontend_worker:
    frontend_address: 127.0.0.1:9095

query_frontend:
  search:
    max_duration: 0

storage:
  trace:
    backend: local
    wal:
      path: /tempo/wal
    local:
      path: /tempo/blocks
